// Code generated by protoc-gen-go. DO NOT EDIT.
// source: servrpc.proto

/*
Package servrpc is a generated protocol buffer package.

It is generated from these files:
	servrpc.proto

It has these top-level messages:
	DeletionRequest
	Empty
	SearchRequest
	SearchResponse
*/
package servrpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeletionRequest struct {
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
}

func (m *DeletionRequest) Reset()                    { *m = DeletionRequest{} }
func (m *DeletionRequest) String() string            { return proto.CompactTextString(m) }
func (*DeletionRequest) ProtoMessage()               {}
func (*DeletionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeletionRequest) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

// Return an error from controller if something went wrong
type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type SearchRequest struct {
	Pattern string `protobuf:"bytes,1,opt,name=pattern" json:"pattern,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SearchRequest) GetPattern() string {
	if m != nil {
		return m.Pattern
	}
	return ""
}

type SearchResponse struct {
	Filename string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	FileSize int64  `protobuf:"varint,2,opt,name=fileSize" json:"fileSize,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SearchResponse) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *SearchResponse) GetFileSize() int64 {
	if m != nil {
		return m.FileSize
	}
	return 0
}

func init() {
	proto.RegisterType((*DeletionRequest)(nil), "servrpc.DeletionRequest")
	proto.RegisterType((*Empty)(nil), "servrpc.Empty")
	proto.RegisterType((*SearchRequest)(nil), "servrpc.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "servrpc.SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PortalController service

type PortalControllerClient interface {
	// Forwards file deletion request from client
	DeleteFile(ctx context.Context, in *DeletionRequest, opts ...grpc.CallOption) (*Empty, error)
	// Forwards search query from Client
	// If there are multiple files that match the query, return them as a stream
	FileSearch(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (PortalController_FileSearchClient, error)
}

type portalControllerClient struct {
	cc *grpc.ClientConn
}

func NewPortalControllerClient(cc *grpc.ClientConn) PortalControllerClient {
	return &portalControllerClient{cc}
}

func (c *portalControllerClient) DeleteFile(ctx context.Context, in *DeletionRequest, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/servrpc.PortalController/DeleteFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portalControllerClient) FileSearch(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (PortalController_FileSearchClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_PortalController_serviceDesc.Streams[0], c.cc, "/servrpc.PortalController/FileSearch", opts...)
	if err != nil {
		return nil, err
	}
	x := &portalControllerFileSearchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type PortalController_FileSearchClient interface {
	Recv() (*SearchResponse, error)
	grpc.ClientStream
}

type portalControllerFileSearchClient struct {
	grpc.ClientStream
}

func (x *portalControllerFileSearchClient) Recv() (*SearchResponse, error) {
	m := new(SearchResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for PortalController service

type PortalControllerServer interface {
	// Forwards file deletion request from client
	DeleteFile(context.Context, *DeletionRequest) (*Empty, error)
	// Forwards search query from Client
	// If there are multiple files that match the query, return them as a stream
	FileSearch(*SearchRequest, PortalController_FileSearchServer) error
}

func RegisterPortalControllerServer(s *grpc.Server, srv PortalControllerServer) {
	s.RegisterService(&_PortalController_serviceDesc, srv)
}

func _PortalController_DeleteFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortalControllerServer).DeleteFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/servrpc.PortalController/DeleteFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortalControllerServer).DeleteFile(ctx, req.(*DeletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortalController_FileSearch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SearchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PortalControllerServer).FileSearch(m, &portalControllerFileSearchServer{stream})
}

type PortalController_FileSearchServer interface {
	Send(*SearchResponse) error
	grpc.ServerStream
}

type portalControllerFileSearchServer struct {
	grpc.ServerStream
}

func (x *portalControllerFileSearchServer) Send(m *SearchResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _PortalController_serviceDesc = grpc.ServiceDesc{
	ServiceName: "servrpc.PortalController",
	HandlerType: (*PortalControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeleteFile",
			Handler:    _PortalController_DeleteFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "FileSearch",
			Handler:       _PortalController_FileSearch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "servrpc.proto",
}

func init() { proto.RegisterFile("servrpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x41, 0x4b, 0xc3, 0x30,
	0x1c, 0xc5, 0x17, 0x45, 0xeb, 0xfe, 0xb0, 0x29, 0x39, 0x68, 0xe9, 0x69, 0xe6, 0x34, 0x0f, 0x16,
	0xd1, 0x8b, 0x57, 0x37, 0x15, 0x8f, 0xa5, 0xfb, 0x04, 0xb1, 0xbe, 0x69, 0x21, 0x4d, 0x62, 0xfa,
	0x9f, 0xa0, 0x5f, 0xc2, 0xaf, 0x2c, 0xae, 0x4d, 0x41, 0x05, 0x8f, 0xbf, 0xbc, 0x3c, 0xf2, 0x7e,
	0xa1, 0x49, 0x8b, 0xf0, 0x16, 0x7c, 0x95, 0xfb, 0xe0, 0xd8, 0xc9, 0xa4, 0x47, 0x75, 0x4e, 0x87,
	0xb7, 0x30, 0xe0, 0xda, 0xd9, 0x12, 0xaf, 0x1b, 0xb4, 0x2c, 0x33, 0x3a, 0x58, 0xd7, 0x06, 0x56,
	0x37, 0x48, 0xc5, 0x4c, 0xcc, 0xc7, 0xe5, 0xc0, 0x2a, 0xa1, 0xbd, 0xbb, 0xc6, 0xf3, 0xbb, 0x3a,
	0xa3, 0xc9, 0x0a, 0x3a, 0x54, 0x2f, 0xb1, 0x95, 0x52, 0xe2, 0x35, 0x33, 0x82, 0xed, 0x4b, 0x11,
	0xd5, 0x03, 0x4d, 0xe3, 0xd5, 0xd6, 0x3b, 0xdb, 0xe2, 0xbf, 0x17, 0x62, 0xb6, 0xaa, 0x3f, 0x90,
	0xee, 0xcc, 0xc4, 0x7c, 0xb7, 0x1c, 0xf8, 0xf2, 0x53, 0xd0, 0x51, 0xe1, 0x02, 0x6b, 0xb3, 0x74,
	0x96, 0x83, 0x33, 0x06, 0x41, 0x5e, 0x13, 0x6d, 0x0d, 0x70, 0x5f, 0x1b, 0xc8, 0x34, 0x8f, 0xa2,
	0xbf, 0xb4, 0xb2, 0xe9, 0x90, 0x74, 0x06, 0x23, 0x79, 0x43, 0xf4, 0xdd, 0xe9, 0xc6, 0xc9, 0xe3,
	0x21, 0xff, 0x21, 0x96, 0x9d, 0xfc, 0x39, 0xef, 0x2c, 0xd4, 0xe8, 0x42, 0x2c, 0x4e, 0x49, 0x56,
	0xae, 0xc9, 0xd7, 0xd5, 0xc6, 0xe7, 0xcf, 0xb0, 0x08, 0x9a, 0xf1, 0xb4, 0x18, 0x77, 0x23, 0xcb,
	0x62, 0x59, 0x88, 0xc7, 0xfd, 0xed, 0x8f, 0x5f, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0xe0, 0x5d,
	0x47, 0xb3, 0x82, 0x01, 0x00, 0x00,
}
